# Generated by Django 4.2.19 on 2025-04-15 12:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_type', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank='')),
                ('photo', models.ImageField(null=True, upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, validators=[product.models.validate_phone])),
                ('message', models.TextField(blank='')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, validators=[product.models.validate_phone])),
                ('status', models.CharField(choices=[('pn', 'В ожидании'), ('cn', 'Обсуждено'), ('cd', 'Успешно завершено'), ('cnd', 'Отменено'), ('rc', 'Повторное обсуждение')], default='Pending', max_length=255)),
                ('region', models.CharField(choices=[('AN', 'Андижан'), ('BU', 'Бухара'), ('FA', 'Фергана'), ('JI', 'Джизак'), ('XO', 'Хорезм'), ('NA', 'Наманган'), ('NG', 'Навои'), ('QA', 'Кашкадарья'), ('QR', 'Каракалпакстан'), ('SA', 'Самарканд'), ('SI', 'Сырдарья'), ('SU', 'Сурхандарья'), ('TO', 'Ташкентская область'), ('TT', 'Город Ташкент')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank='')),
                ('photo', models.ImageField(null=True, upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='product.menu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='product.OrderItem', to='product.product'),
        ),
    ]
