# Generated by Django 4.2.19 on 2025-03-05 09:57

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, validators=[product.models.validate_phone])),
                ('message', models.TextField(blank='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank='')),
                ('photo', models.ImageField(null=True, upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('region', models.CharField(choices=[('AN', 'Andijon'), ('BU', 'Buxoro'), ('FA', 'Farg‘ona'), ('JI', 'Jizzax'), ('XO', 'Xorazm'), ('NA', 'Namangan'), ('NG', 'Navoiy'), ('QA', 'Qashqadaryo'), ('QR', 'Qoraqalpog‘iston'), ('SA', 'Samarqand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TO', 'Toshkent viloyati'), ('TT', 'Toshkent shahri')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.contact')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank='')),
                ('photo', models.ImageField(null=True, upload_to='blog/')),
                ('blog_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.blogtype')),
            ],
        ),
    ]
