# Generated by Django 4.2.19 on 2025-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.FileField(null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Conversion', 'Conversion'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to='product/'),
        ),
    ]
