# Generated by Django 4.2.19 on 2025-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_blog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[], default='key', max_length=255),
            preserve_default=False,
        ),
    ]
