# Generated by Django 4.2.19 on 2025-03-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_blog_photo_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
