# Generated by Django 4.2.19 on 2025-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_order_contact_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='Anasxon', max_length=255),
            preserve_default=False,
        ),
    ]
