# Generated by Django 4.2.19 on 2025-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_menu_key_alter_submenu_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
