# Generated by Django 4.2.19 on 2025-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_menu_key_alter_submenu_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('jsabdckjsa', 'option 1')], max_length=255),
        ),
    ]
