# Generated by Django 4.2.19 on 2025-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_menu_submenu_submenudetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='key',
            field=models.CharField(default='key', max_length=255),
            preserve_default=False,
        ),
    ]
