# Generated by Django 4.2.19 on 2025-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_menu_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='key',
            field=models.CharField(default='key', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
