# Generated by Django 4.2.19 on 2025-04-15 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_submenu_key_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SubMenuDetail',
        ),
    ]
