# Generated by Django 4.2.19 on 2025-04-15 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_blog_description_delete_submenudetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=''),
        ),
    ]
