# Generated by Django 4.2.19 on 2025-04-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='name',
            new_name='label',
        ),
    ]
