# Generated by Django 4.2.19 on 2025-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
